
[package]
name = "cmp-folders"
version = "0.1.0"
edition = "2024"
authors = ["sms1sis"]

[dependencies]

sha2 = "0.10"

blake3 = "1.3"

colored = "3.0"

walkdir = "2.3"

hex = "0.4"

serde = { version = "1.0", features = ["derive"] }

serde_json = "1.0"
